// writer: 'Matthew DuTrumble',
//  biopic: 'matthew.png',
// bio: 'Executive Chef',
// showTitle: 'Zynga',
// showLink: 'http://www.zynga.com'

var recipes = [
//////////////////////SMALL BITES
{
  title: 'Corn Fritters',
  id: 'corn-fritters',
  categoryId: 'small-bites',
  heroImageCount: 2,
  cooktime: '30 minutes',
  serves: '6',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Deviled Eggs',
  id: 'deviled-eggs',
  categoryId: 'small-bites',
  heroImageCount: 3,
  cooktime: '30 minutes',
  serves: '24',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Goat Cheese Crostini',
  id: 'goat-cheese-crostini',
  categoryId: 'small-bites',
  heroImageCount: 3,
  cooktime: '8 minutes',
  serves: '4',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Kate Hudson’s Fig & Burrata Flatbread',
  subtitle: true,
  swapMobileHeroImages: true,
  longTitle: true,
  id: 'kate-hudson-fig',
  categoryId: 'small-bites',
  heroImageCount: 3,
  cooktime: '30 minutes',
  serves: '4',
  writer: 'Kate Hudson',
  hidewriter: true,
  bio: '',
  showTitle: '',
  showLink: ''
},
{
  title: 'Shrimp & Mango Ceviche',
  id: 'shrimp-mango-ceviche',
  categoryId: 'small-bites',
  heroImageCount: 3,
  cooktime: '2 hours, 20 minutes',
  serves: '4',
  writer: 'Tiffany Bendayan',
  bio: '',
  showTitle: 'Broward Saves',
  showLink: 'http://www.browardsaves.com/shrimp-mango-ceviche-recipe-easy-and-healthy-summer-recipe/'
},
{
  title: 'Stuffed Red Potatoes',
  id: 'stuffed-red-potatoes',
  categoryId: 'small-bites',
  heroImageCount: 3,
  cooktime: '38 minutes',
  serves: '20 Potatoes',
  writer: 'Meagan Wied',
  bio: 'Food Writer',
  showTitle: 'A Zesty Bite',
  showLink: 'http://www.azestybite.com/stuffed-red-potatoes'
},
{
  title: 'Summer Harvest Vegetable Soup',
  id: 'summer-harvest-vegetable-soup',
  categoryId: 'small-bites',
  heroImageCount: 3,
  cooktime: '8 - 10 Hours',
  serves: '8',
  writer: 'Stephanie O’Dea',
  bio: '',
  showTitle: 'Crockpot 365',
  showLink: 'http://crockpot365.blogspot.com/2014/06/have-recipe-of-your-very-own-featured.html'
},
{
  title: 'Sweet Potato Fries',
  id: 'sweet-potato-fries',
  categoryId: 'small-bites',
  heroImageCount: 2,
  cooktime: '25 minutes',
  serves: '1 - 2',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
////////////////////////AFTERNOON PLATES
{
  title: 'Bacon Wrapped Chicken Skewers',
  id: 'bacon-wrapped-skewers',
  categoryId: 'afternoon-plates',
  heroImageCount: 3,
  cooktime: '30 minutes',
  serves: '4 - 5 Skewers',
  writer: 'Melissa Griffiths',
  bio: '',
  showTitle: 'Bless This Mess',
  showLink: 'http://www.blessthismessplease.com/2014/05/brown-sugar-bacon-wrapped-chicken-skewers.html'
},
{
  title: 'Corn & Tomato Succotash Summer Salad',
  id: 'corn-tomato-succotash-summer-salad',
  categoryId: 'afternoon-plates',
  heroImageCount: 3,
  cooktime: '30 minutes',
  serves: '10',
  writer: 'Mark Walker',
  biopic: 'markwalker.png',
  bio: 'Executive Chef',
  showTitle: '49 Square Catering',
  showLink: 'http://www.49sqcatering.com/'
},
{
  title: 'Country Biscuit Grilled Cheese',
  id: 'country-biscuit-grilled-cheese',
  categoryId: 'afternoon-plates',
  heroImageCount: 2,
  cooktime: '40 minutes',
  serves: '10 Sandwiches',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Ham, Peach & Jalapeño Grilled Cheese',
  id: 'ham-peach-jalapeno-grilled-cheese',
  categoryId: 'afternoon-plates',
  heroImageCount: 2,
  cooktime: '10 minutes',
  serves: '1',
  writer: 'Nicole Nared',
  bio: '',
  showTitle: 'Brown Sugar',
  showLink: 'http://bsugarmama.com/ham-peach-jalapeno-grilled-cheese-sandwich/'
},
{
  title: 'Spinach Quiche',
  id: 'spinach-quiche',
  categoryId: 'afternoon-plates',
  heroImageCount: 3,
  cooktime: '3 hours',
  serves: '6',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Summer Spinach Salad',
  id: 'summer-spinach-salad',
  categoryId: 'afternoon-plates',
  heroImageCount: 3,
  cooktime: '15 minutes',
  serves: '2',
  writer: 'Tiffany McCauley',
  bio: '',
  showTitle: 'The Gracious Pantry',
  showLink: 'http://www.thegraciouspantry.com/clean-eating-spinach-summer-salad/'
},
{
  title: 'Truffle Mac & Cheese',
  id: 'truffle-mac-cheese',
  categoryId: 'afternoon-plates',
  heroImageCount: 3,
  cooktime: '40 minutes',
  serves: '6',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
/////////////////////////EVENING PLATES
{
  title: 'Barbecued Salmon with Grilled Vegetables',
  longTitle: true,
  id: 'barbecued-salmon-with-grilled-vegetables',
  categoryId: 'evening-plates',
  heroImageCount: 2,
  cooktime: '1 hour',
  serves: '4',
  writer: 'Caroline Barnes',
  bio: '',
  showTitle: 'Do It All Working Mom',
  showLink: 'http://doitallworkingmom.blogspot.ca/2014/04/tin-foil-salmon-and-vegetables-on-bbq.html'
},
{
  title: 'Blackened Catfish',
  id: 'blackened-catfish',
  categoryId: 'evening-plates',
  heroImageCount: 3,
  cooktime: '15 minutes',
  serves: '1',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Chicken Pot Pie',
  id: 'chicken-pot-pie',
  categoryId: 'evening-plates',
  heroImageCount: 4,
  cooktime: '50 minutes',
  serves: '6 - 8',
  writer: 'Virginia',
  bio: 'Food and Gardening Blogger',
  showTitle: 'Ock Du Spock ',
  showLink: 'http://www.ock-du-spock.com/2014/05/chicken-pot-pie-recipe.html#.U_vdvLxdWvY'
},
{
  title: 'Creamy Mint Pasta with Rainbow Beets and Peas',
  id: 'creamy-mint-pasta',
  categoryId: 'evening-plates',
  heroImageCount: 2,
  cooktime: '20 minutes',
  serves: '1',
  writer: 'Laura Miner ',
  bio: 'Recipe Winner, Cook At Home Mom',
  showTitle: '',
  showLink: ''
},
{
  title: 'Eggplant Parmesan',
  id: 'eggplant-parmesan',
  categoryId: 'evening-plates',
  heroImageCount: 2,
  cooktime: '1 hour',
  serves: '6',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Fettuccine with Fresh Peas, Garlic Scapes & Sausage',
  longTitle: true,
  id: 'fettuccine-with-fresh-peas',
  categoryId: 'evening-plates',
  heroImageCount: 3,
  cooktime: '30 minutes',
  serves: '2',
  writer: 'Jillian and Malcolm Bedell',
  bio: '',
  showTitle: 'From Away',
  showLink: 'http://www.fromaway.com/sponsored/farmville-to-table-fettucine-with-fresh-peas-garlic-scapes-and-sausage '
},
{
  title: 'Pan-Seared Trout',
  id: 'pan-seared-trout',
  categoryId: 'evening-plates',
  heroImageCount: 3,
  cooktime: '15 minutes',
  serves: '1',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Pesto-Tomato Chicken with Peach Salsa',
  swapMobileHeroImages: true,
  subtitle: true,
  id: 'pesto-tomato-chicken',
  categoryId: 'evening-plates',
  heroImageCount: 3,
  cooktime: '2.5 Hours',
  serves: '6',
  writer: 'Matthew Bellamy & Kate Hudson',
  hidewriter: true,
  bio: '',
  showTitle: '',
  showLink: ''
},
{
  title: 'Pumpkin Risotto with Gorgonzola & Walnuts',
  longTitle: true,
  swapMobileHeroImages: true,
  id: 'pumpkin-risotto',
  categoryId: 'evening-plates',
  heroImageCount: 3,
  cooktime: '1 hour',
  serves: '4 - 6',
  writer: 'Marc Murphy',
  biopic: 'marc.png',
  bio: 'Chef & regular judge on <br/>Food Network\'s hit show',
  showTitle: 'Chopped',
  showLink: 'http://www.foodnetwork.com/chefs/marc-murphy/bio.html'
},
{
  title: 'Stuffed Bell Pepper ',
  id: 'stuffed-bell-pepper',
  categoryId: 'evening-plates',
  heroImageCount: 3,
  cooktime: '40 minutes',
  serves: '2',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
/////////////////////////SAUCES AND SPREADS
{
  title: 'Cranberry Sauce',
  id: 'cranberry-sauce',
  categoryId: 'sauces-spreads',
  heroImageCount: 2,
  cooktime: '30 minutes',
  serves: '2 cups',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Garlic Hummus',
  id: 'garlic-humus',
  categoryId: 'sauces-spreads',
  heroImageCount: 2,
  cooktime: '15 minutes',
  serves: '6',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Homemade Fresh Pesto',
  id: 'fresh-pesto',
  categoryId: 'sauces-spreads',
  heroImageCount: 2,
  cooktime: '10 minutes',
  serves: '6 ¼ cups',
  writer: 'Rachael Moshman',
  bio: '',
  showTitle: '',
  showLink: ''
},
{
  title: 'Homemade Ricotta Cheese',
  id: 'homemade-ricotta-cheese',
  categoryId: 'sauces-spreads',
  heroImageCount: 2,
  cooktime: '20 minutes',
  serves: '1',
  writer: 'Laura Miner',
  bio: '',
  showTitle: '',
  showLink: ''
},
{
  title: 'Pico de Gallo',
  id: 'pico-de-gallo',
  categoryId: 'sauces-spreads',
  heroImageCount: 1,
  cooktime: '30 minutes',
  serves: '4',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Spinach Dip',
  id: 'spinach-dip',
  categoryId: 'sauces-spreads',
  heroImageCount: 3,
  cooktime: '25 minutes',
  serves: '1 bowl',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Strawberry Balsamic Thyme Jam',
  id: 'strawberry-balsamic-thyme-jam',
  categoryId: 'sauces-spreads',
  heroImageCount: 2,
  cooktime: '1 hour',
  serves: '6 cups',
  writer: 'Rebecca Lindamood',
  bio: 'Food Writer',
  showTitle: 'Foodie with Family',
  showLink: 'http://www.foodiewithfamily.com/2011/06/29/strawberry-balsamic-thyme-freezer-jam/'
},
//////////////////////////BAKING PASTRY
{
  title: 'Apple Fritters',
  id: 'apple-fritter',
  categoryId: 'baking-pastry',
  heroImageCount: 3,
  cooktime: '15 minutes',
  serves: '4',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Beer, Bacon & Cheddar Cornbread',
  id: 'beer-bacon',
  categoryId: 'baking-pastry',
  heroImageCount: 3,
  cooktime: '45 minutes',
  serves: '12',
  writer: 'Mary Evans',
  bio: '',
  showTitle: 'Lovefoodies',
  showLink: 'http://www.lovefoodies.com/beer-bacon--cheddar-cornbread.html'
},
{
  title: 'Biscuits with Goat Cheese & Blueberry Compote',
  longTitle: true,
  id: 'biscuits-with-goat-cheese',
  categoryId: 'baking-pastry',
  heroImageCount: 3,
  cooktime: '1 hour',
  serves: '4 Biscuits',
  writer: 'Cheryl Malik',
  bio: '',
  showTitle: '40 Aprons',
  showLink: 'http://www.40aprons.com'
},
{
  title: 'Blackberry Skillet Cobbler',
  id: 'blackberry-skillet-cobbler',
  categoryId: 'baking-pastry',
  heroImageCount: 3,
  cooktime: '45 minutes',
  serves: 'One 9 inch Pie',
  writer: 'Angie Barrett',
  bio: '',
  showTitle: 'Big Bear’s Wife',
  showLink: 'http://www.bigbearswife.com/2014/06/farmville-to-table-new-farmville-to.html '
},
{
  title: 'Caramel Apple Pie',
  id: 'caramel-apple-pie',
  categoryId: 'baking-pastry',
  heroImageCount: 3,
  cooktime: '45 minutes',
  serves: 'One 9 inch Pie',
  writer: 'Amber',
  bio: '',
  showTitle: 'Bluebonnets & Brownies',
  showLink: 'http://www.bluebonnetsandbrownies.com/2014/05/10/caramel-apple-pie/'
},
{
  title: 'Cherry Cheesecake Cookie Bars',
  id: 'cherry-cheesecake-cookie-bars',
  categoryId: 'baking-pastry',
  heroImageCount: 3,
  cooktime: '50 minutes',
  serves: '12 Bars',
  writer: 'Dakota Whitacre',
  bio: 'Recipe Winner & FarmVille 2 Player',
  showTitle: '',
  showLink: ''
},
{
  title: 'Cinnamon Sugar Apple Crullers',
  id: 'cinnamon-sugar-apple-crullers',
  categoryId: 'baking-pastry',
  heroImageCount: 3,
  cooktime: '1.5 hours',
  serves: '10 – 20 Crullers (depending on desired size)',
  writer: 'Margrit Falley',
  bio: 'Recipe Winner & FarmVille 2 Player',
  showTitle: '',
  showLink: ''
},
{
  title: 'Citrus Ginger Pound Cake',
  id: 'citrus-ginger-pound-cake',
  categoryId: 'baking-pastry',
  heroImageCount: 3,
  cooktime: '1 hour',
  serves: '8',
  writer: 'Laura Miner',
  bio: 'Recipe Winner, Cook At Home Mom',
  showTitle: '',
  showLink: ''
},
{
  title: 'Coffee Cake with Streusel Topping',
  id: 'coffee-cake',
  categoryId: 'baking-pastry',
  heroImageCount: 2,
  cooktime: '30 - 40 minutes',
  serves: '5',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Farmhouse White Bread',
  id: 'farmhouse-white-bread',
  categoryId: 'baking-pastry',
  heroImageCount: 3,
  cooktime: '4 hours',
  serves: '3 Loaves',
  writer: 'Susan, Farmgirl Fare',
  bio: '',
  showTitle: '',
  showLink: ''
},
{
  title: 'Oatmeal Cookies',
  id: 'oatmeal-cookies',
  categoryId: 'baking-pastry',
  heroImageCount: 3,
  cooktime: '15 minutes',
  serves: '1 Dozen Cookies',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Peach Upside-Down Cake',
  id: 'peach-upsidedown-cake',
  categoryId: 'baking-pastry',
  heroImageCount: 3,
  cooktime: '1.5 hours',
  serves: '6',
  writer: 'Linda Walbridge',
  bio: '',
  showTitle: 'The Orange Bee',
  showLink: 'http://theorangebee.wordpress.com/2014/06/09/peach-upside-down-cake/#more-4637'
},
{
  title: 'Pumpkin Scones',
  id: 'pumpkin-scones',
  categoryId: 'baking-pastry',
  heroImageCount: 3,
  cooktime: '50 minutes',
  serves: '6',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Strawberry Shortcake',
  id: 'strawberry-shortcake',
  categoryId: 'baking-pastry',
  heroImageCount: 3,
  cooktime: '1 hour',
  serves: '24',
  writer: 'Anna van Tonder',
  bio: 'Food Writer',
  showTitle: 'Anna Dishes',
  showLink: 'http://www.annadishes.com/strawberry-shortcake-cupcakes-with-whipped-cream-buttercream-frosting/#sthash.L82ebLQy.dpbs'
},
{
  title: 'Triple Berry Coffee Cake',
  id: 'triple-berry-coffee-cake',
  categoryId: 'baking-pastry',
  heroImageCount: 3,
  cooktime: '1 hour',
  serves: '8 (cut into one-inch slices)',
  writer: 'Elaine Young',
  bio: 'Recipe Winner, FarmVille 2 Player',
  showTitle: '',
  showLink: ''
},
{
  title: 'Vanilla Mint Cupcakes',
  id: 'vanilla-mint-cupcakes',
  categoryId: 'baking-pastry',
  heroImageCount: 3,
  cooktime: '40 minutes',
  serves: '1 dozen cupcakes',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
///////////////////////////SWEET TREATS
{
  title: 'Candied Cranberries',
  id: 'candied-cranberries',
  categoryId: 'sweet-treats',
  heroImageCount: 3,
  cooktime: '45 minutes',
  serves: '8',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Honeydew Agua Fresca',
  id: 'honeydew-agua-fresca',
  categoryId: 'sweet-treats',
  heroImageCount: 3,
  cooktime: '15 minutes',
  serves: '8',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'Apple & Raspberry Yogurt Ice Pops',
  id: 'apple-raspberry-yogurt',
  categoryId: 'sweet-treats',
  heroImageCount: 3,
  cooktime: '40 minutes',
  serves: '10 Ice Pops',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
},
{
  title: 'FarmVille’s Strawberry Milkshake',
  id: 'farmville-strawberry-milkshake',
  categoryId: 'sweet-treats',
  heroImageCount: 1,
  cooktime: '15 minutes',
  serves: '4',
  writer: 'Matthew DuTrumble',
  biopic: 'matthew.png',
  bio: 'Executive Chef',
  showTitle: 'Zynga',
  showLink: 'http://www.zynga.com'
}
];

var categories = [
{
  id: 'small-bites',
  categoryName: 'Small Bites',
  heroUrl: '/small-bites/stuffed-red-potatoes',
},
{
  id: 'afternoon-plates',
  categoryName: 'Afternoon Plates',
  heroUrl: '/afternoon-plates/summer-spinach-salad',
},
{
  id: 'evening-plates',
  categoryName: 'Evening Plates',
  heroUrl: '/evening-plates/pesto-tomato-chicken',
},
{
  id: 'sauces-spreads',
  categoryName: 'Sauces & Spreads',
  heroUrl: '/sauces-spreads/pico-de-gallo',
},
{
  id: 'baking-pastry',
  categoryName: 'Baking & Pastry',
  heroUrl: '/baking-pastry/caramel-apple-pie',
},
{
  id: 'sweet-treats',
  categoryName: 'Sweet Treats',
  heroUrl: '/sweet-treats/candied-cranberries',
}
];